### ISSUE TITLE
Support for Romanian language

### ISSUE THREAD

**Issue by DeepReSearcher101** [Welding-Torch/Anonymize_Excel#1]
Hello, thanks for this script. It is working like a charm.
I have a question if I may. Where can I set some params in order to download Spacy for Romanian language and to get all things going, including presidio analyzer?
Thanks!

**Comment by Welding-Torch** [comment]
In order to download Spacy for Romanian language use
```
python -m spacy download ro_core_news_sm
```

Find where `excel_anonymizer.py` is stored by typing 
```
pip show excel-anonymizer
```
and copy the path to your file explorer.

Then **replace the `excel_anonymizer.py` file** with the one I've written for you here: [Romanian Configuration for Excel Anonymizer](https://gist.github.com/Welding-Torch/329f6856051944dc8c336ec243384ada). There is a summary of changes I've made at the bottom of the gist. 

Thanks for using Excel Anonymizer.
